### ISSUE TITLE
drop down obscures tails of the dangly characters

### ISSUE THREAD

**Issue by NerdyMatthew** [ChildishGiant/perdola#2]
![image](https://user-images.githubusercontent.com/18603830/29439420-5acb1642-83b5-11e7-9af5-1433685f752a.png)
![image](https://user-images.githubusercontent.com/18603830/29439423-6392452a-83b5-11e7-93ac-ddd82fdb1896.png)

:'(

**Comment by NerdyMatthew** [comment]
do you want my device and os and version of chrome I'm running etc?

**Comment by ChildishGiant** [comment]
Since it's a cross platform issue, it's not necessary.
